import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:smart_safety_ecosystem/core/design/app_theme.dart';
import 'package:smart_safety_ecosystem/data/app_settings.dart';
import 'package:smart_safety_ecosystem/data/incident_store.dart';
import 'package:smart_safety_ecosystem/domain/models/geo.dart';
import 'package:smart_safety_ecosystem/domain/models/incident.dart';
import 'package:smart_safety_ecosystem/domain/models/lora.dart';
import 'package:smart_safety_ecosystem/domain/models/severity.dart';
import 'package:smart_safety_ecosystem/main.dart';
import 'package:smart_safety_ecosystem/state/app_controller.dart';
import 'package:smart_safety_ecosystem/ui/screens/about_screen.dart';
import 'package:smart_safety_ecosystem/ui/screens/diagnostics_screen.dart';
import 'package:smart_safety_ecosystem/ui/shell/app_navigation.dart';

/// Review widths: narrow phone, large phone, small/medium tablet, large
/// tablet, small desktop, desktop, wide desktop.
const List<double> kReviewWidths = <double>[
  360,
  414,
  600,
  768,
  1000,
  1280,
  1600,
  1920,
];

Future<AppController> controllerWithRecords() async {
  SharedPreferences.setMockInitialValues(<String, Object>{
    'settings.advancedMode': true,
  });
  final settings = await AppSettings.load();
  final store = IncidentStore();

  await store.add(
    Incident(
      id: 'a',
      category: IncidentCategory.accident,
      origin: IncidentOrigin.demo,
      occurredAt: DateTime(2026, 3, 1, 10),
      status: IncidentStatus.active,
      severity: Severity.critical,
      summary: 'Impact 5.2 g, rollover detected',
      deviceId: 'VN-01',
      location: GeoFix(
        latitude: 12.9716,
        longitude: 77.5946,
        fixedAt: DateTime(2026, 3, 1, 10),
        satellites: 9,
        accuracyMetres: 4,
      ),
      deliveryOutcome: TransmissionOutcome.sentUnacknowledged,
      attempts: 2,
      acknowledgements: 0,
      notes: const ['Generated by Demo Mode. Not a real event.'],
    ),
  );
  await store.add(
    Incident(
      id: 'b',
      category: IncidentCategory.screening,
      origin: IncidentOrigin.demo,
      occurredAt: DateTime(2026, 3, 1, 11),
      status: IncidentStatus.acknowledged,
      severity: Severity.caution,
      summary: 'Wearable screening: high risk band',
      deviceId: 'WB-01',
      riskScore: 86,
      band: 'High risk',
    ),
  );

  return AppController(settings: settings, incidentStore: store);
}

/// Navigates to [destination] using whichever navigation the current width has.
Future<void> navigateTo(
  WidgetTester tester,
  AppDestination destination,
  double width,
) async {
  final usesBottomBar = width < kSideNavBreakpoint;

  if (!usesBottomBar) {
    await tester.tap(
      find.descendant(
        of: find.byType(AppNavigation),
        matching: find.text(destination.label),
      ),
    );
    return;
  }

  if (AppDestination.bottomBarPrimary.contains(destination)) {
    await tester.tap(
      find.descendant(
        of: find.byType(NavigationBar),
        matching: find.text(destination.label.split(' ').first),
      ),
    );
    return;
  }

  await tester.tap(
    find.descendant(
      of: find.byType(NavigationBar),
      matching: find.byIcon(Icons.more_horiz),
    ),
  );
  await tester.pumpAndSettle();
  await tester.tap(find.text(destination.label).last);
}

/// Matches Breakpoints.expanded, where side navigation takes over.
const double kSideNavBreakpoint = 1000;

/// Asserts that no layout exception is pending, and if there is one, reports the
/// text inside the overflowing subtree so the failure points at the widget
/// rather than at a pixel count.
void expectNoLayoutError(WidgetTester tester, String reason) {
  final error = tester.takeException();
  if (error == null) return;

  String? nearbyText;
  void find(RenderObject node) {
    if (nearbyText != null) return;
    if (node is RenderFlex && node.toString().contains('OVERFLOWING')) {
      final found = <String>{};
      void collect(RenderObject child) {
        for (final m in RegExp(r'"([^"]{2,60})"').allMatches(child.toStringDeep())) {
          found.add(m.group(1)!);
        }
      }

      RenderObject? ancestor = node;
      RenderObject? best = node;
      while (ancestor != null) {
        if (ancestor is RenderFlex && ancestor.direction == Axis.vertical) {
          best = ancestor;
          if (ancestor.parent is RenderFlex) break;
        }
        ancestor = ancestor.parent;
      }
      if (best != null) best.visitChildren(collect);
      nearbyText = found.take(10).join(' / ');
      return;
    }
    node.visitChildren(find);
  }

  find(tester.binding.renderViews.first);
  fail('$reason\n$error\nNearby text: ${nearbyText ?? 'not found'}');
}

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  tearDown(() {
    SharedPreferences.setMockInitialValues(<String, Object>{});
  });

  // One test per width. Resizing the view part-way through a single test
  // invalidates render objects mid-frame and produces framework-level
  // assertions that say nothing about the application, so each width gets a
  // clean pump lifecycle instead.
  for (final width in kReviewWidths) {
    testWidgets('all screens lay out cleanly at ${width.toInt()}px',
        (tester) async {
      tester.view.physicalSize = Size(width, 1000);
      tester.view.devicePixelRatio = 1.0;
      addTearDown(tester.view.reset);

      final controller = await controllerWithRecords();
      addTearDown(controller.dispose);

      // Produce a live wearable reading so result-dependent layouts are covered.
      controller.setRunning(true);
      await tester.pump(const Duration(milliseconds: 600));
      controller.setRunning(false);

      await tester.pumpWidget(SmartSafetyApp(controller: controller));
      await tester.pumpAndSettle();
      expect(tester.takeException(), isNull);

      for (final destination in AppDestination.values) {
        await navigateTo(tester, destination, width);
        await tester.pumpAndSettle();

        expectNoLayoutError(
          tester,
          '${destination.label} overflowed or threw at ${width.toInt()}px',
        );
        // The destination is actually on screen.
        expect(find.text(destination.label), findsWidgets);
      }
    });
  }

  for (final width in kReviewWidths) {
    testWidgets('secondary pages lay out at ${width.toInt()}px', (tester) async {
      tester.view.physicalSize = Size(width, 1400);
      tester.view.devicePixelRatio = 1.0;
      addTearDown(tester.view.reset);

      for (final theme in <ThemeData>[AppTheme.light, AppTheme.dark]) {
        for (final page in <Widget>[const DiagnosticsScreen(), const AboutScreen()]) {
          await tester.pumpWidget(MaterialApp(theme: theme, home: page));
          await tester.pumpAndSettle();
          expect(
            tester.takeException(),
            isNull,
            reason: '$page threw at ${width.toInt()}px',
          );
        }
      }
    });
  }

  for (final width in kReviewWidths) {
    testWidgets('large text scale survives ${width.toInt()}px', (tester) async {
      tester.view.physicalSize = Size(width, 1000);
      tester.view.devicePixelRatio = 1.0;
      addTearDown(tester.view.reset);

      final controller = await controllerWithRecords();
      addTearDown(controller.dispose);

      controller.setRunning(true);
      await tester.pump(const Duration(milliseconds: 600));
      controller.setRunning(false);

      // 1.6x is the clamp the app itself applies.
      tester.platformDispatcher.textScaleFactorTestValue = 1.6;
      addTearDown(tester.platformDispatcher.clearTextScaleFactorTestValue);

      await tester.pumpWidget(SmartSafetyApp(controller: controller));
      await tester.pumpAndSettle();

      for (final destination in AppDestination.values) {
        await navigateTo(tester, destination, width);
        await tester.pumpAndSettle();
        expectNoLayoutError(
          tester,
          '${destination.label} broke at 1.6x text, ${width.toInt()}px',
        );
      }
    });
  }
}